# Generated by Django 3.0.6 on 2020-06-05 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_auto_20200605_2306'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
